name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  status:
    required: true
  steps:
    default: '{}'
  jobName:
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
