name: Notify to Slack
description: Notify job status to Slack, with context and useful links
author: François Best
branding:
  icon: send
  color: red
inputs:
  status:
    required: true
  steps:
    default: '{}'
  jobName:
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
