name: Notify to Slack
description: Notify job status to Slack, with context and useful links
author: François Best
branding:
  icon: send
  color: red
inputs:
  status:
    required: true
    description: 'The status of the job'
  steps:
    description: 'Set to `toJson(steps)` (in double curly-braces) to detail out successful/failed steps'
    required: false
    default: '{}'
  jobName:
    description: 'The name of the job'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
