name: Test name
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: install-dependencies
        run: yarn
      - id: build
        run: yarn build
      - id: lint
        run: yarn lint
      - id: package
        run: yarn package
      - id: test
        run: yarn test
      - uses: ./
        if: always()
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        if: ${{ !env.ACT }}
      - uses: actions/checkout@v2
        if: ${{ env.ACT }}
        with:
          path: actions-slack-notify
      - uses: ./
        if: always()
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
